### PR TITLE
IDAS: notify amd users if driver is too new (thanks amd)

### PR DESCRIPTION
**Pull request by EmiMidnight**
AMD redid their opengl driver and managed to break everything in the process. For the time being, probably a good idea to let people know if their driver is too new, so they don't wonder why the game keeps crashing immediately on boot. 

(nez plz fix i wanna play d8)

### CODE REVIEW

**Comment by EmiMidnight** [comment]
Hm, not sure why the CI check fails. Compiles perfectly fine under VS2019? God damnit.

**Comment by EmiMidnight** [comment]
Ah. Maybe I should include the assembly reference... fixed.

**Comment by Nezarn** [comment]
Proper fix will be made when amd stops breaking stuff every update.

**Comment by Arapose** [comment]
Same problem goes from the Lindbergh games on AMD, since the new update also broke their games:

Virtua Fighter 5 is a lot more glitchy than before
After Burner Climax doesn't start up
Let's Go Jungle having more graphical issues with most of the objects now being invisible
2Spicy is completely blank and unplayable
Sega Race TV being completely unplayable with super large cars, just like when the game was loaded without an shader patch

HOTD4, Rambo, R-Tuned, and OutRun 2 SP SDX are fine, as this update did improve much of those games' performances.

**Pull request merged**
