### PR TITLE
corrected and added some informations in GameProfiles and Descriptions

### PR DESCRIPTION
**Pull request by andrea-petrucci-1975**

### CODE REVIEW

**Comment by Harmmmm** [comment]
Cool thanks again.

**Comment by Harmmmm** [comment]
btw isnt Point blank ES4?

**Comment by ReaverTeknoGods** [comment]
Point Blank X is ES4, I used to have the original pcb. Web sucks and is full of inaccurate info

**Comment by Poliwrath** [comment]
https://github.com/Shizmob/arcade-docs
This *should* be more reliable than most sites / forums

**Comment by andrea-petrucci-1975** [comment]
i updated PointBlankX.json with ES4

**Pull request merged**
