### PR TITLE
A bunch of changes

### PR DESCRIPTION
**Pull request by Poliwrath**
Notable changes:
Add a "silent mode" option (requested by Harm) to hide the loader console window
Add a patreon bool to the game XML files (and I made sure to update the revisions this time, sorry)

Changed a bunch of other stuff on the code side of things.

### CODE REVIEW

**Comment by ReaverTeknoGods** [comment]
Please remove png compressor and bat file.

**Comment by ReaverTeknoGods** [comment]
Ford Racing and Sega Rally 3 are both Europa-R games. They use different I/O revisions, which is why the packages are a bit different.

**Comment by ReaverTeknoGods** [comment]
Even GRID is Europa-R game but uses a bit different injection type.

**Comment by Poliwrath** [comment]
> Please remove png compressor and bat file.

done!

> Ford Racing and Sega Rally 3 are both Europa-R games. They use different I/O revisions, which is why the packages are a bit different.

I made the Sega Rally 3 IO pipe thing inherit the Europa-R one since it was mostly the same code except for the transmit stuff

**Pull request merged**
