### PR TITLE
Added Enable Outputs bool

### PR DESCRIPTION
**Pull request by Boomslangnz**
to load OutputBlaster.dll or disable on games that support

### CODE REVIEW

**Comment by ReaverTeknoGods** [comment]
cannot merge pls fix

**Comment by Boomslangnz** [comment]
Dunno, nothing is messed with what I've done. I've double checked and triple checked it all. Think appveyor just being dumb

**Comment by Poliwrath** [comment]
you just have to update the profilerevision in gameprofiles I think

**Comment by Boomslangnz** [comment]
ok all fixed now

**Pull request merged**
