### PR TITLE
Remember last played game

### PR DESCRIPTION
**Pull request by Poliwrath**
Very tiny QoL change

### CODE REVIEW

**Comment by ReaverTeknoGods** [comment]
You should also add option in Emulator Settings for "Load last played game by default on launch" for those who don't want it.

**Comment by Poliwrath** [comment]
Done! I put the option right beside the "use mouse for gun" option at the top of the window

**Comment by ReaverTeknoGods** [comment]
Come to discord claim your 10$ bounty.

**Comment by Poliwrath** [comment]
Hi, nibs★#3148 is me

**Pull request merged**
