### PR TITLE
Added Otushu DX xml to TPUI.

### PR DESCRIPTION
**Pull request by EmuAl**

### CODE REVIEW

**Comment by Harmmmm** [comment]
You don't have to add the XML file to the project file manually.

**Comment by Harmmmm** [comment]
Plus please check test menu setup

**Comment by EmuAl** [comment]
i can only assume you have blocked me on discord because you don't answer me, so i'll put it here

thats the only one i see that could be wrong 
but i'm not sure if it means
test menu is the game executable or test menu is it's own executable, not very clear as to which one, i went with the first one ?

<TestMenuParameter>-t</TestMenuParameter>
  <TestMenuIsExecutable>true</TestMenuIsExecutable>
  <ExtraParameters></ExtraParameters>
  <TestMenuExtraParameters></TestMenuExtraParameters>
  <IconName>Icons\OtushuDX.png</IconName>
  <EmulationProfile>APM3</EmulationProfile>
  <GameProfileRevision>0</GameProfileRevision>
  <Is64Bit>true</Is64Bit>
  <HasSeparateTestMode>false</HasSeparateTestMode>

the -t command is in the batch file in the game folder
has seperate testmode i think is asking if it has its own exe ? which i can't see ?
i don't see anything else wrong ?

**Comment by Harmmmm** [comment]
HasSeparateTestMode: enables the test menu on/off thing in the ui so enable this when a game doesnt have a ingame way to go the test menu pressing the test button. (so when its a seperate exe or same exe with argument)

TestMenuIsExecutable: enable this when the test menu is a seperate exe

**Comment by EmuAl** [comment]
thanks for the help

**Pull request closed without merging**
