### PR TITLE
ExecutableName Updates

### PR DESCRIPTION
**Pull request by EllimistArcade**
First round of updates to ExecutableNames. Filling in some blanks. Also fixing some ones that were incorrectly capitalized.

### CODE REVIEW

**Comment by EllimistArcade** [comment]
Updated Revision Numbers.

**Comment by EmiMidnight** [comment]
Looks okay to me. One thing though, if you only change the description json then you don't need to increase the profile version. Versions only relevant for actual profile xml changes.

**Comment by EmiMidnight** [comment]
Is it fine to merge this now or should I wait for more changes?

**Comment by EllimistArcade** [comment]
Fine to merge now, that will let me sync my fork and then I can submit the rest of my changes next week.

**Pull request merged**
