### PR TITLE
Fix pixelated game icons

### PR DESCRIPTION
**Pull request by EmiMidnight**
Game icons looked kinda ugly because of basically nearest neighbor filtering, especially in the library. This just sets it to filter the icons.

### CODE REVIEW

**Comment by Poliwrath** [comment]
Turns out this caused issues on Windows 8 so that's why we reverted it in the past, #304, so I'm reverting this until we detect OS or something. Sorry!

**Comment by EmiMidnight** [comment]
Typical MS, jeez. Yeah, reverting seems to be the best option, sorry about that. :(

**Comment by EmiMidnight** [comment]
This might be the cause: https://github.com/dotnet/wpf/issues/3762
I see that icons have been ran through tinypng now, which would turn them into 8bit pngs.  Really stupid bug on the windows side though, love how their response seems to be "Well, it's fixed in Windows 10 lol."

**Comment by Poliwrath** [comment]
>_>
Thanks for looking into it a bit more, icons aren't 'updatable' (?_?), so we'd have to delete em all for Windows 8 users, which is probably not going to happen...

**Comment by EmiMidnight** [comment]
I'm working on a workaround right now, but I... don't have any windows 8 machines to test it on. :|

**Pull request merged**
