### PR TITLE
Upgrade Battle Gear 4 to PRO

### PR DESCRIPTION
**Pull request by Exmach**
TODO: fix dual jvs, add missing controls

### CODE REVIEW

**Comment by ReaverTeknoGods** [comment]
Please add each JVS package emulation to own function.

**Comment by ReaverTeknoGods** [comment]
Did you try various other JVS games with this new code? I am worried it could break compatibility 🐙

**Comment by Exmach** [comment]
Seems MK broken, i need to make new packages bg4 only

**Comment by ReaverTeknoGods** [comment]
did u ever finish this?

**Comment by Exmach** [comment]
No, i stuck with MT locked in game

**Comment by ReaverTeknoGods** [comment]
Maybe it is because of jvs info? like more buttons or similar need to be added?

**Comment by Exmach** [comment]
all i know is same problem with regular bg4 exists (and i dunno who and how fixed it)

**Pull request closed without merging**
