### PR TITLE
added missing xml attributes in game profiles

### PR DESCRIPTION
**Pull request by andrea-petrucci-1975**

### CODE REVIEW

**Comment by Nezarn** [comment]
They're not missing, unused attributes are false by default.

**Comment by andrea-petrucci-1975** [comment]
ok, then many useless attributes that have been set to false should be deleted

**Comment by andrea-petrucci-1975** [comment]
example: https://ibb.co/N30LZtF

**Comment by Poliwrath** [comment]
not really necessary

**Pull request closed without merging**
